config/routes.rb
Rails.application.routes.draw do

  resources :customers
  root to: 'home#index'
  resources :instruments
  devise_for :users

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :instruments
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
	belongs_to :customer
	
end
	

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def index
		@customers = Customer.all
		respond_to do |format|
		  format.json do
		  	render json: @customers.to_json(include: [instruments: { only: [:kind, :model]}])
		  end
		  format.html do
		  	render 'index'
		  end
		end
	end

	def show
		@customer = Customer.find_by(id: params[:id])
	    respond_to do |format|
	    	format.json do
	    		render json: @customer.to_json(include: [instruments: { only: [:kind, :model]}])
	    	end
	    	format.html do
	    		render 'show'
	    	end
	    end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController

	def index
		@instruments = Instrument.all
	end

	def create
		@instrument = Instrument.create(instrument_params)
		render json: @instrument
	end

	def instrument_params
		params.require(:instrument).permit(:kind, :model, :customer_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/customers/_customer.html.erb
<b><a href="/customers<%=customer.id%>"><%= customer.name %></a></b><br>
<% customer.instruments.each do |instrument| %>
  <p><%= instrument.model %> <%= instrument.kind %></p>
<% end %><br>

app/views/customers/index.html.erb
<script>  
  $(document).ready(function(event){
    loadCustomers()
  })  
</script>

app/views/home/index.html.erb
<h2>Welcome to Instrumental</h2>
<p>Use the 'customers' tab to manage rentals.</p>

app/views/instruments/_instrument.html.erb
<p><%= instrument.model %> <%= instrument.kind %></p>

app/views/instruments/index.html.erb
<h2>All Instruments</h2>
<%= render @instruments %>

app/views/layouts/_messages.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if flash[:error] %>
  <p class="error"><%= safe_join(flash[:error], "<br>".html_safe) %></p>
<% end %>

app/views/layouts/_navigation.html.erb
<nav>
    <%= link_to "Home", root_path %> ||
    <%= link_to "Log In", new_user_session_path %> ||
    <%= link_to "Sign Up", new_user_registration_path %> ||
    <%= link_to "Log Out", destroy_user_session_path, method: 'delete' %> ||
    <%= link_to "Customers", customers_path, id: "customers_index" %> ||
    <%= link_to "Instruments", instruments_path %> ||
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instrumental2</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= render '/layouts/navigation' %>

<%= render '/layouts/messages' %>

<div id="app_container">
  <%= yield %>
</div>

</body>
</html>